function makeLexRule(type,name,ignore,regex,tokenizer){
  if (typeof type !='string'||type ==''){throw new Error("type must be a nonempty string");}
  if (typeof name !='string'||name ==''){throw new Error("name must be a nonempty string");}
  if (typeof ignore !='boolean'){throw new Error("ignore must be a boolean");}
  if (!(regex instanceof RegExp)||regex.source[0]!='^'){throw new Error("regex needs to be a Regular Expression starting with '^'");}
  if (typeof tokenizer !='function'){throw new Error("unexpected tokenizer for rule");}
  return {
    type:type,
    name:name,
    ignore:ignore,
    regex:regex,
    tokenizer:tokenizer
  }
}

const lexRules = [
  makeLexRule( 
    'spacer',
    'whitespace',
    true,     
    /^\s+/,
    (val)=>val,
  ),
  makeLexRule( 
    'comment',
    'line_comment',
    true,     
    /^\/\/[^\n]*/,
    (val)=>val,
  ),
  makeLexRule( 
    'comment',
    'block_comment',
    true,     
    /^\/\*[\s\S]*?\*\//,
    (val)=>val,
  ),
  makeLexRule( 
    'bracket',
    'Lparenthesis',
    false,
    /^\(/,
    (val)=>val,
  ),
  makeLexRule( 
    'bracket',
    'Rparenthesis',
    false,
    /^\)/,
    (val)=>val,
  ),
  makeLexRule( 
    'bracket',
    'Lsquare',
    false,
    /^\[/,
    (val)=>val,
  ),
  makeLexRule( 
    'bracket',
    'Rsquare',
    false,
    /^\]/,
    (val)=>val,
  ),
  makeLexRule( 
    'bracket',
    'Lcurly',
    false,
    /^\{/,
    (val)=>val,
  ),
  makeLexRule( 
    'bracket',
    'Rcurly',
    false,
    /^\}/,
    (val)=>val,
  ),
  makeLexRule( 
    'num',
    'decimal',
    false,
    /^[0-9]+(\.[0-9]+)?/,
    (value) =>Number(value),
  ),
  makeLexRule( 
    'ident',
    'identity',
    false,
    /^[A-Za-z_]\w*/,
    (val)=>val,
  ),
  makeLexRule( 
    'operator',
    'hat',
    false,
    /^\^/,
    (val)=>val,
  ),
  makeLexRule( 
    'operator',
    'slash',
    false,
    /^\//,
    (val)=>val,
  ),
  makeLexRule( 
    'operator',
    'star',
    false,
    /^\*/,
    (val)=>val,
  ),
  makeLexRule( 
    'operator',
    'dash',
    false,
    /^\-/,
    (val)=>val,
  ),
  makeLexRule( 
    'operator',
    'plus',
    false,
    /^\+/,
    (val)=>val,
  ),
]

module.exports = {
  lexRules,
}